sudo: false
language: node_js
node_js:
- 5.1.1

script:
- npm test
- npm run e2e
# - cd src
# - cat ../coverage/lcov.info | ../node_modules/coveralls/bin/coveralls.js

notifications:
  slack:
    secure: MPEurDUvYfcl3b5Hji/42sKF6TQLRcrkqMfKINy6buFePKdbkwDjQd+r0GYAC153lLpbJeiFy7p8TAVp2QP3wmC02ea9n3CG8juKpCBabyaZq3RBvhJ7kKUd/BdTLPNWU1ttSrQlzOoAs3HcuEAaeUzhW3d0LPH+bVvYx4aG8UM=
