sudo: false
language: node_js
node_js:
- '0.12.4'
before_install:
- npm install -g jspm@0.16.0-beta
- jspm config registries.github.auth $JSPM_GITHUB_TOKEN
- jspm install
- jspm install --dev
script:
- gulp ci:travis
- cd src
- cat ../coverage/lcov.info | ../node_modules/coveralls/bin/coveralls.js
env:
  global:
  - secure: Tkvy2f+j1Z2Pl4LgZB2jtYmnr4WqvGzycLbJu/RuJHL6hL3GdHqCP54qfC45iBB+B6U2JG6+oDGFlh2cQlWwQjZhUIHZ58CcTBrkSo53T3XxS7DM/aWGY63wWgp7oU7/vQKnJWT9DkBlMD5ACIIfa+y13zZKekOx8JBKt65P12A=
