language: node_js

node_js:
  - "0.10"

before_install:
  - npm install -g jspm
  - jspm install

script:
  - gulp travis
  - cd src
  - cat ../coverage/lcov.info | ../node_modules/coveralls/bin/coveralls.js
